export const Sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origin: ["italy"],
    stars: 4.5,
    imageUrl: "/assets/foods/food-1.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    cookTime: "20-30",
    price: 20,
    favorite: true,
    origin: ["persia", " middle east", "china"],
    stars: 5,
    imageUrl: "/assets/foods/food-2.png",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    cookTime: "10-15",
    price: 5,
    favorite: false,
    origin: ["germany"],

    stars: 3.5,
    imageUrl: "/assets/foods/food-3.png",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    cookTime: "10-15",
    price: 2,
    favorite: true,
    origin: ["belgium", "france"],
    stars: 3,
    imageUrl: "/assets/foods/food-4.png",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chiken Soup",
    cookTime: "40-50",
    price: 11,
    favorite: false,
    origin: ["India"],
    stars: 3.5,
    imageUrl: "/assets/foods/food-5.png",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegitable Pizza",
    cookTime: "40-50",
    price: 9,
    favorite: false,
    origin: ["Italy"],
    stars: 4.5,
    imageUrl: "/assets/foods/food-6.png",
    tags: ["FastFood", "Pizza"],
  },
];

// export const sample_tags = [
//   { name: "All", count: 6 },
//   { name: "FastFood", count: 4 },
//   { name: "Pizza", count: 2 },
//   { name: "Lunch", count: 2 },
//   { name: "SlowFood", count: 2 },
//   { name: " Hamburger", count: 1 },
//   { name: "Fry", count: 1 },
//   { name: "Soup", count: 1 },
// ];
